/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.timezone;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import java.util.TimeZone;
import java.util.Locale;
import org.appcelerator.kroll.KrollDict;

@Kroll.module(name = "Titimezone", id = "ti.timezone")
public class TitimezoneModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "TitimezoneModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public TitimezoneModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is
		// created
	}

	// Properties
	@Kroll.getProperty
	public KrollDict getDefaultTimezone() {
		TimeZone tz = TimeZone.getDefault();
		KrollDict res = new KrollDict();
		res.put("short",tz.getDisplayName(false, TimeZone.SHORT));
		res.put("long",tz.getDisplayName(false, TimeZone.LONG));
		res.put("id",tz.getID());
		return res;
	}
	

}
