/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.timezone;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import java.util.TimeZone;
import org.appcelerator.kroll.KrollDict;

@Kroll.module(name = "Titimezone", id = "ti.timezone")
public class TitimezoneModule extends KrollModule {

	public TitimezoneModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
	}

	@Kroll.getProperty
	public KrollDict getDefaultTimezone() {
		TimeZone tz = TimeZone.getDefault();
		KrollDict res = new KrollDict();
		res.put("short", tz.getDisplayName(false, TimeZone.SHORT));
		res.put("long", tz.getDisplayName(false, TimeZone.LONG));
		res.put("id", tz.getID());
		res.put("offset", (int) tz.getRawOffset());
		return res;
	}
}
